# fly.toml file generated for discord-b-bot on 2022-12-30T23:10:11+09:00

app = "discord-b-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "bt0724/b_bot:1.2.0"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
