name: cd

on:
  workflow_run:
    workflows: [ci]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      -
        name: get version tag
        uses: SebRollen/toml-action@v1.0.1
        id: read_toml
        with:
          file: 'Cargo.toml'
          field: 'package.version'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -i bt0724/b_bot:${{ steps.read_toml.outputs.value }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}